services:
  execution:
    image: ethereum/client-go:stable
    command: >
      --sepolia
      --http
      --http.addr 0.0.0.0
      --http.api eth,net,web3
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /geth/jwt.hex
    volumes:
      - ./geth-data:/root/.ethereum
      - ./jwt.hex:/geth/jwt.hex:ro
    ports:
      - '8545:8545'
      - '8551:8551'
      - '30303:30303'

  consensus:
    image: sigp/lighthouse:latest
    command: >
      lighthouse bn
      --network=sepolia
      --execution-endpoint=http://execution:8551
      --execution-jwt=/lighthouse/jwt.hex
      --http
      --http-address=0.0.0.0
      --checkpoint-sync-url=https://sepolia.beaconstate.info
    volumes:
      - ./lighthouse-data:/root/.lighthouse
      - ./jwt.hex:/lighthouse/jwt.hex:ro
    depends_on:
      - execution
    ports:
      - '9000:9000'
      - '5052:5052'